# Generated by Django 2.2.5 on 2020-10-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20201020_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidmobility',
            name='retailRecreation',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
