# Generated by Django 2.2.5 on 2020-10-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20201021_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCountryProvinceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_region_code', models.CharField(default=0, max_length=30)),
                ('country_region', models.CharField(default=0, max_length=30)),
                ('sub_region_1', models.CharField(default=0, max_length=30)),
                ('sub_region_2', models.CharField(default=0, max_length=30)),
                ('metro_area', models.CharField(default=0, max_length=30)),
                ('iso_3166_2_code', models.CharField(default=0, max_length=30)),
                ('census_fips_code', models.CharField(default=0, max_length=30)),
                ('retail_and_recreation_percent_change_from_baseline', models.CharField(default=0, max_length=30)),
                ('grocery_and_pharmacy_percent_change_from_baseline', models.CharField(default=0, max_length=30)),
                ('parks_percent_change_from_baseline', models.CharField(default=0, max_length=30)),
                ('transit_stations_percent_change_from_baseline', models.CharField(default=0, max_length=30)),
                ('workplaces_percent_change_from_baseline', models.CharField(default=0, max_length=30)),
                ('residential_percent_change_from_baseline', models.CharField(default=0, max_length=30)),
                ('date', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
