# Generated by Django 2.2.5 on 2020-10-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_worldcountryprovincerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalEmployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=0, max_length=30)),
                ('month', models.CharField(default=0, max_length=30)),
                ('day', models.CharField(default=0, max_length=30)),
                ('emp_combined', models.CharField(default=0, max_length=30)),
                ('country_region', models.CharField(default=0, max_length=30)),
                ('emp_combined_inclow', models.CharField(default=0, max_length=30)),
                ('emp_combined_incmiddle', models.CharField(default=0, max_length=30)),
                ('emp_combined_inchigh', models.CharField(default=0, max_length=30)),
                ('emp_combined_ss40', models.CharField(default=0, max_length=30)),
                ('emp_combined_ss60', models.CharField(default=0, max_length=30)),
                ('emp_combined_ss65', models.CharField(default=0, max_length=30)),
                ('emp_combined_ss70', models.CharField(default=0, max_length=30)),
                ('emp_combined_advance', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
