# Generated by Django 2.2.5 on 2020-10-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_nationalemployment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalemployment',
            name='country_region',
        ),
    ]
