# Generated by Django 2.2.5 on 2020-11-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_consumerspending'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCountiesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(default=0, max_length=30)),
                ('country', models.CharField(default=0, max_length=30)),
                ('state', models.CharField(default=0, max_length=30)),
                ('county', models.CharField(default=0, max_length=30)),
                ('level', models.CharField(default=0, max_length=30)),
                ('lat', models.CharField(default=0, max_length=30)),
                ('locationId', models.CharField(default=0, max_length=30)),
                ('long', models.CharField(default=0, max_length=30)),
                ('population', models.CharField(default=0, max_length=30)),
                ('metrics_testPositivityRatio', models.CharField(default=0, max_length=30)),
                ('metrics_caseDensity', models.CharField(default=0, max_length=30)),
                ('metrics_contactTracerCapacityRatio', models.CharField(default=0, max_length=30)),
                ('metrics_infectionRate', models.CharField(default=0, max_length=30)),
                ('metrics_infectionRateCI90', models.CharField(default=0, max_length=30)),
                ('metrics_icuHeadroomRatio', models.CharField(default=0, max_length=30)),
                ('metrics_icuHeadroomDetails', models.CharField(default=0, max_length=30)),
                ('riskLevels_overall', models.CharField(default=0, max_length=30)),
                ('riskLevels_testPositivityRatio', models.CharField(default=0, max_length=30)),
                ('riskLevels_caseDensity', models.CharField(default=0, max_length=30)),
                ('riskLevels_contactTracerCapacityRatio', models.CharField(default=0, max_length=30)),
                ('riskLevels_infectionRate', models.CharField(default=0, max_length=30)),
                ('riskLevels_icuHeadroomRatio', models.CharField(default=0, max_length=30)),
                ('actuals_cases', models.CharField(default=0, max_length=30)),
                ('actuals_deaths', models.CharField(default=0, max_length=30)),
                ('actuals_positiveTests', models.CharField(default=0, max_length=30)),
                ('actuals_negativeTests', models.CharField(default=0, max_length=30)),
                ('actuals_contactTracers', models.CharField(default=0, max_length=30)),
                ('actuals_hospitalBeds_capacity', models.CharField(default=0, max_length=30)),
                ('actuals_hospitalBeds_currentUsageTotal', models.CharField(default=0, max_length=30)),
                ('actuals_hospitalBeds_currentUsageCovid', models.CharField(default=0, max_length=30)),
                ('actuals_hospitalBeds_typicalUsageRate', models.CharField(default=0, max_length=30)),
                ('actuals_icuBeds_capacity', models.CharField(default=0, max_length=30)),
                ('actuals_icuBeds_currentUsageTotal', models.CharField(default=0, max_length=30)),
                ('actuals_icuBeds_currentUsageCovid', models.CharField(default=0, max_length=30)),
                ('actuals_icuBeds_typicalUsageRate', models.CharField(default=0, max_length=30)),
                ('actuals_newCases', models.CharField(default=0, max_length=30)),
                ('lastUpdatedDate', models.CharField(default=0, max_length=30)),
            ],
        ),
    ]
