# Generated by Django 2.2.5 on 2020-11-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_historicalcountiesrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_cases',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_contactTracers',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_deaths',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_hospitalBeds_capacity',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_hospitalBeds_currentUsageCovid',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_hospitalBeds_currentUsageTotal',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_hospitalBeds_typicalUsageRate',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_icuBeds_capacity',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_icuBeds_currentUsageCovid',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_icuBeds_currentUsageTotal',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_icuBeds_typicalUsageRate',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_negativeTests',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_newCases',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='actuals_positiveTests',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='country',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='county',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='fips',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='lastUpdatedDate',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='lat',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='level',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='locationId',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='long',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='metrics_caseDensity',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='metrics_contactTracerCapacityRatio',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='metrics_icuHeadroomDetails',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='metrics_icuHeadroomRatio',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='metrics_infectionRate',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='metrics_infectionRateCI90',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='metrics_testPositivityRatio',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='population',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='riskLevels_caseDensity',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='riskLevels_contactTracerCapacityRatio',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='riskLevels_icuHeadroomRatio',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='riskLevels_infectionRate',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='riskLevels_overall',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='riskLevels_testPositivityRatio',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalcountiesrecord',
            name='state',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
    ]
